package com.chapchap.customer.global.observability.customerai;

public enum CustomerAiDiagnosticEventType {
    CONSULTATION_RESULT,
    CONSULTATION_FAILED,
    KNOWLEDGE_SUBMITTED,
    KNOWLEDGE_SUBMISSION_FAILED,
    KNOWLEDGE_CALLBACK_RESULT,
    SUMMARY_SUBMITTED,
    SUMMARY_SUBMISSION_FAILED,
    SUMMARY_CALLBACK_RESULT,
    CURRENT_STATE_ACCESS_GRANTED,
    CURRENT_STATE_ACCESS_DENIED
}
