package com.chapchap.customer.domain.audit.entity;

public enum AuditActionType {
    FAQ_CREATED,
    FAQ_UPDATED,
    FAQ_DEACTIVATED,
    CONSULTATION_ESCALATED,
    CONSULTATION_ACCEPTED,
    QUALITY_INQUIRY_PROCESSED,
    KNOWLEDGE_VERSION_REGISTERED,
    KNOWLEDGE_VERSION_ACTIVATED,
    KNOWLEDGE_PROCESSING_FAILED
}
