package com.chapchap.customer.domain.audit.constant;

public enum AuditActionType {
    FAQ_CREATED,
    FAQ_UPDATED,
    FAQ_DEACTIVATED,
    CONSULTATION_ESCALATED,
    CONSULTATION_ACCEPTED,
    CONSULTATION_CLOSED,
    AI_SUMMARY_GENERATED,
    AI_SUMMARY_FAILED,
    QUALITY_INQUIRY_PROCESSED,
    KNOWLEDGE_VERSION_REGISTERED,
    KNOWLEDGE_VERSION_ACTIVATED,
    KNOWLEDGE_PROCESSING_FAILED
}
